sudo: false

language: node_js

node_js:
  - "8"

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  slack: astrocoders:pKUMdVeYN9SItr4nYetvSSqC

stages:
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: test:
      script:
        - npm test
    - deploy:
      script:
        - git config --global user.email "grsabreu@users.noreply.github.com"
        - git config --global user.name "Gabriel Bot"
        - echo "machine github.com login grsabreu password $GITHUB_TOKEN" > ~/.netrc
        - cd website && yarn install && GIT_USER=grsabreu npm run publish-gh-pages
