name: Update Docs

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, build, and test
      run: |
        cd website && npm ci
      env:
        CI: true
    - name: Use Node.js ${{ matrix.node-version }}
      uses: clay/docusaurus-github-action@master
      with:
        args: deploy
        DEPLOY_SSH_KEY: ${{ secrets.GITHUB_TOKEN }}
        BUILD_DIR: website
        PROJECT_NAME: reform
